'use strict';
// ─── DAL: tasks (human follow-up reminders) ────────────────────────────────
// Distinct from Sequences (automated/bot-sent) — a task is a reminder for a
// HUMAN, optionally auto-created when a contact/deal lands on a pipeline
// stage configured with `reminder_days` (server/lib/stage-reminders.js).
const { query } = require('../index');

async function list(companyId, { status, contactId, dueBefore, limit = 200, offset = 0 } = {}) {
  if (!companyId) throw new Error('tasks.list requires companyId');
  const conditions = ['t.company_id = $1'];
  const params = [companyId];
  let idx = 2;
  if (status) { conditions.push(`t.status = $${idx++}`); params.push(status); }
  if (contactId) { conditions.push(`t.contact_id = $${idx++}`); params.push(contactId); }
  if (dueBefore) { conditions.push(`t.due_at <= $${idx++}`); params.push(dueBefore); }
  const lim = Math.min(parseInt(limit, 10) || 200, 500);
  const off = Math.max(parseInt(offset, 10) || 0, 0);
  const r = await query(
    `SELECT t.*, c.name AS contact_name, c.email AS contact_email, d.title AS deal_title
       FROM tasks t
       JOIN contacts c ON c.id = t.contact_id
       LEFT JOIN deals d ON d.id = t.deal_id
      WHERE ${conditions.join(' AND ')}
      ORDER BY t.due_at ASC
      LIMIT $${idx++} OFFSET $${idx++}`,
    [...params, lim, off]
  );
  return r.rows;
}

async function create(companyId, { contactId, dealId, title, notes, dueAt, autoGenerated = false, sourcePipelineKey, sourceStageKey }) {
  if (!companyId) throw new Error('tasks.create requires companyId');
  if (!contactId) throw new Error('tasks.create requires contactId');
  if (!title || !title.trim()) throw new Error('title is required');
  if (!dueAt) throw new Error('dueAt is required');
  const r = await query(
    `INSERT INTO tasks (company_id, contact_id, deal_id, title, notes, due_at, auto_generated, source_pipeline_key, source_stage_key)
     VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) RETURNING *`,
    [companyId, contactId, dealId || null, title.trim(), notes || null, dueAt, autoGenerated, sourcePipelineKey || null, sourceStageKey || null]
  );
  return r.rows[0];
}

// Auto-generated reminders are idempotent per (contact, deal, stage) while
// pending — ON CONFLICT DO NOTHING means a contact re-advancing through the
// same stage twice before the first reminder is resolved does not pile up
// duplicates. Returns null (not an error) on the conflict path.
async function createAutoIfAbsent(companyId, { contactId, dealId, title, dueAt, sourcePipelineKey, sourceStageKey }) {
  const r = await query(
    `INSERT INTO tasks (company_id, contact_id, deal_id, title, due_at, auto_generated, source_pipeline_key, source_stage_key)
     VALUES ($1,$2,$3,$4,$5,true,$6,$7)
     ON CONFLICT (contact_id, COALESCE(deal_id, '00000000-0000-0000-0000-000000000000'::uuid), source_stage_key)
       WHERE auto_generated = true AND status = 'pending'
     DO NOTHING
     RETURNING *`,
    [companyId, contactId, dealId || null, title, dueAt, sourcePipelineKey || null, sourceStageKey || null]
  );
  return r.rows[0] || null;
}

async function get(companyId, id) {
  const r = await query(
    `SELECT t.*, c.name AS contact_name, c.email AS contact_email, d.title AS deal_title
       FROM tasks t JOIN contacts c ON c.id = t.contact_id LEFT JOIN deals d ON d.id = t.deal_id
      WHERE t.company_id=$1 AND t.id=$2`,
    [companyId, id]
  );
  return r.rows[0] || null;
}

async function update(companyId, id, { title, notes, dueAt, status }) {
  const sets = [], params = []; let i = 1;
  if (title !== undefined) { sets.push(`title=$${i++}`); params.push(title); }
  if (notes !== undefined) { sets.push(`notes=$${i++}`); params.push(notes); }
  if (dueAt !== undefined) { sets.push(`due_at=$${i++}`); params.push(dueAt); }
  if (status !== undefined) {
    if (!['pending', 'done'].includes(status)) throw new Error("status must be 'pending' or 'done'");
    sets.push(`status=$${i++}`); params.push(status);
    sets.push(`completed_at=${status === 'done' ? 'now()' : 'NULL'}`);
  }
  if (!sets.length) return get(companyId, id);
  params.push(companyId, id);
  const r = await query(
    `UPDATE tasks SET ${sets.join(', ')}, updated_at=now() WHERE company_id=$${i++} AND id=$${i} RETURNING *`,
    params
  );
  return r.rows[0] || null;
}

async function remove(companyId, id) {
  const r = await query(`DELETE FROM tasks WHERE company_id=$1 AND id=$2 RETURNING id`, [companyId, id]);
  return r.rowCount;
}

async function countDueByStatus(companyId, status = 'pending') {
  const r = await query(
    `SELECT COUNT(*) FILTER (WHERE due_at <= now()) AS overdue,
            COUNT(*) FILTER (WHERE due_at > now() AND due_at <= now() + interval '1 day') AS due_today,
            COUNT(*)::int AS total
       FROM tasks WHERE company_id=$1 AND status=$2`,
    [companyId, status]
  );
  const row = r.rows[0];
  return { overdue: parseInt(row.overdue, 10), due_today: parseInt(row.due_today, 10), total: row.total };
}

module.exports = { list, create, createAutoIfAbsent, get, update, remove, countDueByStatus };
